name: app_cyclone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  flutter_svg: 1.1.6
  go_router: ^13.2.0
  flutter_bloc: ^8.1.4
  flutter_localization: ^0.2.0
  intl: any
  shared_preferences: ^2.2.2
  carousel_slider: ^4.2.1
  firebase_core: ^2.27.1
  font_awesome_flutter: ^10.7.0
  firebase_auth: ^4.18.0
  firebase_auth_platform_interface: ^7.2.0
  cloud_firestore: ^4.15.10
  flutter_staggered_grid_view: ^0.7.0
  provider: ^6.1.2
  syncfusion_flutter_datepicker: ^25.1.38
  dotted_line: ^3.2.2
  book_my_seat: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
